
USE GlobalstoreDB;


-- Calculate the main business KPIs
SELECT
    SUM(sales) AS Total_Sales,
    SUM(profit) AS Total_Profit,
    COUNT(DISTINCT order_id) AS Total_Orders,
    COUNT(DISTINCT customer_id) AS Total_Customers,
    SUM(quantity) AS Total_Quantity
FROM dbo.[Sample - Superstore Cleaned];


-- Calculate monthly revenue and profit
SELECT
    order_year,
    order_month,
    month_name,
    year_month,

    -- Total revenue generated during the month
    SUM(sales) AS Monthly_Revenue,

    -- Total profit earned during the month
    SUM(profit) AS Monthly_Profit,

    -- Number of units sold during the month
    SUM(quantity) AS Units_Sold,

    -- Count unique orders, not individual product rows
    COUNT(DISTINCT order_id) AS Total_Orders

FROM dbo.[Sample - Superstore Cleaned]

-- Group transactions into individual months
GROUP BY
    order_year,
    order_month,
    month_name,
    year_month

-- Sort months chronologically
ORDER BY
    order_year,
    order_month;


-- Find the top 10 products by total sales
SELECT TOP 10
    product_id,
    product_name,
    category,
    sub_category,

    -- Total units sold for each product
    SUM(quantity) AS Units_Sold,

    -- Total revenue generated by each product
    SUM(sales) AS Total_Sales,

    -- Total profit generated by each product
    SUM(profit) AS Total_Profit

FROM dbo.[Sample - Superstore Cleaned]

-- Calculate results separately for each product
GROUP BY
    product_id,
    product_name,
    category,
    sub_category

-- Show the products with the highest revenue first
ORDER BY
    Total_Sales DESC;

-- Find the top 10 customers by total sales
SELECT TOP 10
    customer_id,
    customer_name,
    segment,

    -- Total revenue generated by each customer
    SUM(sales) AS Total_Sales,

    -- Total profit from each customer's purchases
    SUM(profit) AS Total_Profit,

    -- Count each order once
    COUNT(DISTINCT order_id) AS Total_Orders

FROM dbo.[Sample - Superstore Cleaned]

-- Group all transactions by customer
GROUP BY
    customer_id,
    customer_name,
    segment

-- Rank customers by revenue, highest first
ORDER BY
    Total_Sales DESC;


-- Analyze business performance by region
SELECT
    region,

    -- Total revenue generated in each region
    SUM(sales) AS Total_Sales,

    -- Total profit earned in each region
    SUM(profit) AS Total_Profit,

    -- Total units sold in each region
    SUM(quantity) AS Total_Quantity,

    -- Number of distinct orders in each region
    COUNT(DISTINCT order_id) AS Total_Orders,

    -- Calculate profit margin as a percentage of sales
    CASE
        WHEN SUM(sales) = 0 THEN 0
        ELSE SUM(profit) * 100.0 / SUM(sales)
    END AS Profit_Margin_Percent

FROM dbo.[Sample - Superstore Cleaned]

-- Create one result row per region
GROUP BY region

-- Display regions with the highest sales first
ORDER BY
    Total_Sales DESC;


-- Analyze profit and loss using the profit_status feature
SELECT
    profit_status,

    -- Count transaction rows in each profit group
    COUNT(*) AS Transaction_Rows,

    -- Sales generated by each profit group
    SUM(sales) AS Total_Sales,

    -- Net profit or loss for each group
    SUM(profit) AS Total_Profit,

    -- Units sold in each group
    SUM(quantity) AS Total_Quantity,

    -- Average discount in each group
    AVG(discount) AS Average_Discount

FROM dbo.[Sample - Superstore Cleaned]

-- Separate profitable and loss-making rows
GROUP BY profit_status

-- Show the largest profit contribution first
ORDER BY
    Total_Profit DESC;


-- Identify products whose combined profit is negative
SELECT
    product_id,
    product_name,
    SUM(sales) AS Total_Sales,
    SUM(profit) AS Total_Profit
FROM dbo.[Sample - Superstore Cleaned]
GROUP BY
    product_id,
    product_name
HAVING SUM(profit) < 0
ORDER BY
    Total_Profit ASC;

-- Analyze sales performance year by year
SELECT
    order_year,

    -- Total revenue generated during each year
    SUM(sales) AS Total_Sales,

    -- Total profit earned during each year
    SUM(profit) AS Total_Profit,

    -- Total quantity sold during each year
    SUM(quantity) AS Total_Quantity,

    -- Number of distinct orders in each year
    COUNT(DISTINCT order_id) AS Total_Orders

FROM dbo.[Sample - Superstore Cleaned]

-- Group transactions by year
GROUP BY order_year

-- Display years from earliest to latest
ORDER BY
    order_year ASC;


-- Compare business performance across product categories
SELECT
    category,

    -- Total revenue for each category
    SUM(sales) AS Total_Sales,

    -- Total profit or loss for each category
    SUM(profit) AS Total_Profit,

    -- Total units sold in each category
    SUM(quantity) AS Total_Quantity,

    -- Number of distinct orders containing each category
    COUNT(DISTINCT order_id) AS Total_Orders,

    -- Calculate category profit margin
    CASE
        WHEN SUM(sales) = 0 THEN 0
        ELSE SUM(profit) * 100.0 / SUM(sales)
    END AS Profit_Margin_Percent

FROM dbo.[Sample - Superstore Cleaned]

-- Group transactions by product category
GROUP BY category

-- Display categories with the highest sales first
ORDER BY
    Total_Sales DESC;

